#
# Automagically generated by Approximatrix Simply Fortran 2.24
#
FC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\ar.exe"
WRC="C:\PROGRA~2\SIMPLY~1\MINGW-~1\bin\windres.exe"
RM=rm -f

IDIR=

LDIR=-LC:/PROGRA~2/SIMPLY~1/MINGW-~1/lib/ 


OPTFLAGS= -g

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\basis1.o": ".\basis1.f95" "modules\types.mod" "modules\constants.mod" "modules\strings.mod" "modules\fact.mod" "modules\dispmodule.mod"
	@echo Compiling .\basis1.f95
	@$(FC) -c -o "build\basis1.o" $(FFLAGS) ".\basis1.f95"
"modules\basis.mod" : "build\basis1.o" .EXISTSONLY
	@echo Compiling .\basis1.f95
	@$(FC) -c -o "build\basis1.o" $(FFLAGS) ".\basis1.f95"

"build\constants.o": ".\constants.f95" "modules\types.mod"
	@echo Compiling .\constants.f95
	@$(FC) -c -o "build\constants.o" $(FFLAGS) ".\constants.f95"
"modules\constants.mod" : "build\constants.o" .EXISTSONLY
	@echo Compiling .\constants.f95
	@$(FC) -c -o "build\constants.o" $(FFLAGS) ".\constants.f95"

"build\dispmodule_util.o": ".\dispmodule_util.f95" "modules\putstrmodule.mod"
	@echo Compiling .\dispmodule_util.f95
	@$(FC) -c -o "build\dispmodule_util.o" $(FFLAGS) ".\dispmodule_util.f95"
"modules\dispmodule_util.mod" "modules\dispmodule.mod" : "build\dispmodule_util.o" .EXISTSONLY
	@echo Compiling .\dispmodule_util.f95
	@$(FC) -c -o "build\dispmodule_util.o" $(FFLAGS) ".\dispmodule_util.f95"

"build\fact.o": ".\fact.f95"
	@echo Compiling .\fact.f95
	@$(FC) -c -o "build\fact.o" $(FFLAGS) ".\fact.f95"
"modules\fact.mod" : "build\fact.o" .EXISTSONLY
	@echo Compiling .\fact.f95
	@$(FC) -c -o "build\fact.o" $(FFLAGS) ".\fact.f95"

"build\main.o": ".\main.f95" "modules\basis.mod" "modules\dispmodule.mod" "modules\fact.mod"
	@echo Compiling .\main.f95
	@$(FC) -c -o "build\main.o" $(FFLAGS) ".\main.f95"

"build\precmod.o": ".\precmod.f90"
	@echo Compiling .\precmod.f90
	@$(FC) -c -o "build\precmod.o" $(FFLAGS) ".\precmod.f90"
"modules\precision.mod" : "build\precmod.o" .EXISTSONLY
	@echo Compiling .\precmod.f90
	@$(FC) -c -o "build\precmod.o" $(FFLAGS) ".\precmod.f90"

"build\putstrmodule.o": ".\putstrmodule.f95"
	@echo Compiling .\putstrmodule.f95
	@$(FC) -c -o "build\putstrmodule.o" $(FFLAGS) ".\putstrmodule.f95"
"modules\putstrmodule.mod" : "build\putstrmodule.o" .EXISTSONLY
	@echo Compiling .\putstrmodule.f95
	@$(FC) -c -o "build\putstrmodule.o" $(FFLAGS) ".\putstrmodule.f95"

"build\stringmod.o": ".\stringmod.f90" "modules\precision.mod"
	@echo Compiling .\stringmod.f90
	@$(FC) -c -o "build\stringmod.o" $(FFLAGS) ".\stringmod.f90"
"modules\strings.mod" : "build\stringmod.o" .EXISTSONLY
	@echo Compiling .\stringmod.f90
	@$(FC) -c -o "build\stringmod.o" $(FFLAGS) ".\stringmod.f90"

"build\types.o": ".\types.f95"
	@echo Compiling .\types.f95
	@$(FC) -c -o "build\types.o" $(FFLAGS) ".\types.f95"
"modules\types.mod" : "build\types.o" .EXISTSONLY
	@echo Compiling .\types.f95
	@$(FC) -c -o "build\types.o" $(FFLAGS) ".\types.f95"

clean: .SYMBOLIC
	@echo Deleting build\basis1.o and related files
	@$(RM) "build\basis1.o" "modules\basis.mod"
	@echo Deleting build\constants.o and related files
	@$(RM) "build\constants.o" "modules\constants.mod"
	@echo Deleting build\dispmodule_util.o and related files
	@$(RM) "build\dispmodule_util.o" "modules\dispmodule_util.mod" "modules\dispmodule.mod"
	@echo Deleting build\fact.o and related files
	@$(RM) "build\fact.o" "modules\fact.mod"
	@echo Deleting build\main.o and related files
	@$(RM) "build\main.o"
	@echo Deleting build\precmod.o and related files
	@$(RM) "build\precmod.o" "modules\precision.mod"
	@echo Deleting build\putstrmodule.o and related files
	@$(RM) "build\putstrmodule.o" "modules\putstrmodule.mod"
	@echo Deleting build\stringmod.o and related files
	@$(RM) "build\stringmod.o" "modules\strings.mod"
	@echo Deleting build\types.o and related files
	@$(RM) "build\types.o" "modules\types.mod"
	@echo Deleting target.exe
	@$(RM) "target.exe"

"target.exe":  "build\basis1.o" "build\constants.o" "build\dispmodule_util.o" "build\fact.o" "build\main.o" "build\precmod.o" "build\putstrmodule.o" "build\stringmod.o" "build\types.o" "build\basis.prj.target"
	@echo Generating target.exe
	@$(FC) -o "target.exe" -static "build\basis1.o" "build\constants.o" "build\dispmodule_util.o" "build\fact.o" "build\main.o" "build\precmod.o" "build\putstrmodule.o" "build\stringmod.o" "build\types.o" $(LDIR) $(PRJ_LFLAGS)

all: "target.exe" .SYMBOLIC

